DELIMITER $$

CREATE PROCEDURE p1(min INT, max INT)
BEGIN 
	DECLARE done INT DEFAULT FALSE;
	DECLARE va INT;
	DECLARE cur CURSOR(pmin INT, pmax INT) FOR SELECT a FROM t1 WHERE a BETWEEN pmin AND pmax;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done=TRUE;
	OPEN cur(min, max)
	read_loop: LOOP
		FETCH cur INTO va;
		IF done THEN
			LEAVE read_loop;
		END IF;
		INSERT INTO t1 VALUES (va, 'new');
	END LOOP;
	CLOSE cur;
END;
$$

DELIMITER ;
